services:
  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - "5001:5001"
    restart: always
    container_name: backend
    
  frontend:
    build: 
      context: ./frontend/client
      dockerfile: Dockerfile
      args:
        REACT_APP_URL: http://localhost:5001
    ports: 
      - "3000:80"
    restart: always
    container_name: frontend
    depends_on:
      - backend